version: '3'
services:
  web:
    build: docker
    container_name: django
    volumes:
      - .:/code
      - static:/code/static
      - media:/code/media
    expose:
      - 8000:8000
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn --workers=3 projectname.wsgi -b 0.0.0.0:8080"

  nginx:
    restart: always
    build: nginx
    volumes:
    - ./nginx/:/etc/nginx/conf.d
    - ./logs/:/code/logs
    - static:/code/static
    - media:/code/media
    ports:
      - "1221:80"
    links:
      - web
volumes:
  media:
  static:
