version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/django
    container_name: django
    volumes:
      - .:/taist_app
      - static:/taist_app/static
      - media:/taist_app/media
    command: bash -c "python manage.py collectstatic --no-input &&gunicorn --workers=1 config.wsgi -b 0.0.0.0:8080"

  nginx:
    restart: always
    build:
      context: .
      dockerfile: docker/nginx
    volumes:
      - ./docker/django.conf:/etc/nginx/conf.d/django.conf
      - ./logs/:/taist_app/logs
      - static:/taist_app/static
      - media:/taist_app/media
    ports:
      - "1221:80"
    links:
      - web
volumes:
  media:
  static:
